name: GitHub Activity
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Generate Snake SVG
        uses:Platane/snk@master
        with:
          user: bhedanikhilkumar-code
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg
      
      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]" 
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "generated snake animation" || exit 0
          git push